GET http://localhost:3000

###

GET http://localhost:3000/products

###

POST http://localhost:3000/products
Content-Type: application/json

{
    "productCode": "SHAB-205",
    "productName": "Hyundai Sonata 2024",
    "productLine": "Classic Cars",
    "productScale": "1:12",
    "productVendor": "Exoto Design",
    "productDescription": "Lo que tu quieras",
    "quantityInStock": 4800,
    "buyPrice": 568000,
    "MSRP": 215.60
}

###
GET http://localhost:3000/products/SHAB-204


###
GET http://localhost:3000/products/topten