version: '3.8'

services:
  test-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3001:3000
    restart: always
    env_file:
      - test.env
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    env_file:
      - test.env
    cap_add:
      - SYS_NICE
    environment:
      - MYSQL_DATABASE=classicmodels
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - '3309:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db:
    driver: local
